name: Rails-Rspec-Deploy

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  setup_and_test_execution:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
    - uses: actions/checkout@v2
    - name: Setup Ruby Version
      uses: actions/setup-ruby@master
      with:
        ruby-version: 2.6.x

    - name: Install dependent libralies
      run: sudo apt-get install libmysqlclient-dev

    - name: Setup bundler
      run: gem install bundler

    - name: bundle install
      run: |
        bundle install --jobs 4 --retry 3

    - name: Setup Database
      run: |
        cp config/database.yml.ci config/database.yml
        sudo systemctl start mysql
        bundle exec rails db:create
        bundle exec rails db:schema:load
      env:
        RAILS_ENV: test

    - name: Run RSpec
      run: bundle exec rspec
      env: 
        RAILS_ENV: test

    - name: Archive rspec result screenshots
      if: failure()
      uses: actions/upload-artifact@v1
      with:
        name: rspec result screenshots
        path: tmp/screenshots/

    - name: Set up
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        USER_NAME: ${{ secrets.USER_NAME }}
        HOST_NAME: ${{ secrets.HOST_NAME }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOST_NAME} 'cd Empathy &&
        git pull origin main &&
        ~/.rbenv/shims/bundle install &&
        ~/.rbenv/shims/bundle exec rails assets:precompile RAILS_ENV=production &&
        ~/.rbenv/shims/bundle exec rails db:migrate RAILS_ENV=production &&
        if [[ -e tmp/pids/puma.pid ]];then kill $(cat tmp/pids/puma.pid); echo kill puma process;fi &&
        ~/.rbenv/shims/rails s -e production'